@echo off
echo Initializing git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Renaming branch...
git branch -M main
echo Configuring remote...
git remote remove origin 2>nul
git remote add origin https://github.com/Clickin/Clickin.github.io.git
echo Pushing...
git push -u origin main --force
echo Done.
pause
